package com.pojo;

import java.util.Date;

public class School {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BBS.SCHOOL.SCHOOLID
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	private Short schoolid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BBS.SCHOOL.SCHOOLNAME
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	private String schoolname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BBS.SCHOOL.SCHOOLADDRESS
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	private String schooladdress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BBS.SCHOOL.SCHOOLCREATETIME
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	private Date schoolcreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BBS.SCHOOL.SCHOOLTYPE
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	private String schooltype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BBS.SCHOOL.SCHOOLID
	 * @return  the value of BBS.SCHOOL.SCHOOLID
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public Short getSchoolid() {
		return schoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BBS.SCHOOL.SCHOOLID
	 * @param schoolid  the value for BBS.SCHOOL.SCHOOLID
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public void setSchoolid(Short schoolid) {
		this.schoolid = schoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BBS.SCHOOL.SCHOOLNAME
	 * @return  the value of BBS.SCHOOL.SCHOOLNAME
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public String getSchoolname() {
		return schoolname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BBS.SCHOOL.SCHOOLNAME
	 * @param schoolname  the value for BBS.SCHOOL.SCHOOLNAME
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public void setSchoolname(String schoolname) {
		this.schoolname = schoolname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BBS.SCHOOL.SCHOOLADDRESS
	 * @return  the value of BBS.SCHOOL.SCHOOLADDRESS
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public String getSchooladdress() {
		return schooladdress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BBS.SCHOOL.SCHOOLADDRESS
	 * @param schooladdress  the value for BBS.SCHOOL.SCHOOLADDRESS
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public void setSchooladdress(String schooladdress) {
		this.schooladdress = schooladdress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BBS.SCHOOL.SCHOOLCREATETIME
	 * @return  the value of BBS.SCHOOL.SCHOOLCREATETIME
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public Date getSchoolcreatetime() {
		return schoolcreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BBS.SCHOOL.SCHOOLCREATETIME
	 * @param schoolcreatetime  the value for BBS.SCHOOL.SCHOOLCREATETIME
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public void setSchoolcreatetime(Date schoolcreatetime) {
		this.schoolcreatetime = schoolcreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BBS.SCHOOL.SCHOOLTYPE
	 * @return  the value of BBS.SCHOOL.SCHOOLTYPE
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public String getSchooltype() {
		return schooltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BBS.SCHOOL.SCHOOLTYPE
	 * @param schooltype  the value for BBS.SCHOOL.SCHOOLTYPE
	 * @mbg.generated  Mon Nov 12 09:39:41 CST 2018
	 */
	public void setSchooltype(String schooltype) {
		this.schooltype = schooltype;
	}
}